# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fb5618581bddc652d7cbb1cd0a7c6f16d95aaf8726913cffe236182bdffae403f31d47db9876499edeb36407caf47eb99fc1b620eabd1796b5c3432207031b7

test:
  secret_key_base: b182399be8a2c5c13426da07ccb60bb8cb7e30411ae7b04a00693d14ae286617f51597563930299687611ce00513601e4ce6d277ae448869a881387b53aedc30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
